import { ProductSchema, type Product } from "./schemas";

export const sampleProducts = [
  {
    id: "cw-bat-kookaburra-ghost",
    name: "Kookaburra Ghost Pro Cricket Bat 2024",
    price: 3850000,
    originalPrice: 4500000,
    image: "/images/products/IMG-20230731-WA0015.jpg",
    rating: 5,
    reviews: 48,
    category: "bats",
    badge: "Best Seller",
    info: "Grade 1 English Willow Cricket Bat with Natural Finish",
    description: "The Kookaburra Ghost Pro offers exceptional balance, lightweight pickup, and maximum sweet spot profile designed for professional power hitters.",
    images: [
      "/images/products/IMG-20230731-WA0015.jpg",
      "/images/products/IMG-20230731-WA0016.jpg",
      "/images/products/IMG-20230731-WA0017.jpg",
    ],
  },
  {
    id: "cw-bat-ss-ton-gladiator",
    name: "SS TON Gladiator English Willow Cricket Bat",
    price: 4950000,
    originalPrice: 5800000,
    image: "/images/products/IMG-20230731-WA0016.jpg",
    rating: 5,
    reviews: 36,
    category: "bats",
    badge: "Popular",
    info: "Super Premium Grade 1+ English Willow with Embossed Chrome Sticker",
    description: "Crafted by master bat makers in India, the SS TON Gladiator features massive 40mm contoured edges, round 12-piece cane handle, and extraordinary ping.",
    images: [
      "/images/products/IMG-20230731-WA0016.jpg",
      "/images/products/IMG-20230731-WA0018.jpg",
      "/images/products/IMG-20230731-WA0019.jpg",
    ],
  },
  {
    id: "cw-pads-mrf-grand-edition",
    name: "MRF Grand Edition Batting Legguard Pads",
    price: 1450000,
    originalPrice: 1750000,
    image: "/images/products/IMG-20230731-WA0021.jpg",
    rating: 4.8,
    reviews: 52,
    category: "pads",
    badge: "Pro Choice",
    info: "High Density Foam Legguard with Gel-Zone Knee Protection",
    description: "Endorsed by international test players, these batting pads offer supreme protection against 150km/h fast bowling without restricting running between wickets.",
    images: [
      "/images/products/IMG-20230731-WA0021.jpg",
      "/images/products/IMG-20230731-WA0022.jpg",
      "/images/products/IMG-20230731-WA0023.jpg",
    ],
  },
  {
    id: "cw-gloves-sg-savage-pro",
    name: "SG Savage Pro Batting Gloves Leather Palm",
    price: 780000,
    originalPrice: 950000,
    image: "/images/products/IMG-20230731-WA0030.jpg",
    rating: 4.9,
    reviews: 64,
    category: "gloves",
    badge: "Trending",
    info: "Premium Pittards Sheep Leather Palm with Split Finger Sausage Protection",
    description: "Designed for supreme comfort and grip flexibility in tropical humidity. Reinforced fiber inserts in lead fingers safeguard against high impacts.",
    images: [
      "/images/products/IMG-20230731-WA0030.jpg",
      "/images/products/IMG-20230731-WA0031.jpg",
      "/images/products/IMG-20230731-WA0032.jpg",
    ],
  },
  {
    id: "cw-helmet-shrey-masterclass",
    name: "Shrey Masterclass AIR Cricket Helmet Titanium",
    price: 2150000,
    originalPrice: 2500000,
    image: "/images/products/IMG-20230731-WA0045.jpg",
    rating: 5,
    reviews: 29,
    category: "helmets",
    badge: "Safety Rated",
    info: "BS 7928:2013 Certified Titanium Grille Featherlight Protection",
    description: "Weighing just 750 grams, the Shrey Masterclass AIR provides unmatched ventilation and concussion safety standard compliant across all ICC matches.",
    images: [
      "/images/products/IMG-20230731-WA0045.jpg",
      "/images/products/IMG-20230731-WA0046.jpg",
      "/images/products/IMG-20230731-WA0047.jpg",
    ],
  },
  {
    id: "cw-kitbag-kookaburra-pro",
    name: "Kookaburra Pro Wheelie Cricket Kitbag Large",
    price: 1850000,
    originalPrice: 2200000,
    image: "/images/products/IMG-20230731-WA0054.jpg",
    rating: 4.7,
    reviews: 41,
    category: "bags",
    badge: "Heavy Duty",
    info: "Heavy Duty 1680D Cordura Construction with Internal Bat Cave for 3 Bats",
    description: "Spacious heavy-duty wheelie bag capable of holding full cricket equipment including 2 pairs of pads, 3 bats, 4 gloves, helmet, and footwear.",
    images: [
      "/images/products/IMG-20230731-WA0054.jpg",
      "/images/products/IMG-20230731-WA0055.jpg",
      "/images/products/IMG-20230731-WA0056.jpg",
    ],
  },
  {
    id: "cw-shoes-asics-speed-menace",
    name: "ASICS Speed Menace Cricket Spike Shoes",
    price: 1650000,
    originalPrice: 1950000,
    image: "/images/products/IMG-20230731-WA0061.jpg",
    rating: 4.8,
    reviews: 33,
    category: "shoes",
    badge: "Popular",
    info: "FlyteFoam Midsole with Removable Steel Spikes for Turf Pitches",
    description: "Engineered specifically for fast bowlers and agile batsmen, offering optimal ankle lock, turf grip, and shock absorption upon landing.",
    images: [
      "/images/products/IMG-20230731-WA0061.jpg",
      "/images/products/IMG-20230731-WA0062.jpg",
      "/images/products/IMG-20230731-WA0063.jpg",
    ],
  },
  {
    id: "cw-balls-dukes-special-match",
    name: "Dukes Special Match Leather Cricket Ball (Box of 6)",
    price: 1200000,
    originalPrice: 1400000,
    image: "/images/products/IMG-20230731-WA0070.jpg",
    rating: 5,
    reviews: 77,
    category: "balls",
    badge: "Match Quality",
    info: "Hand Stitched 4-Piece Alum Tanned English Leather 156g",
    description: "The gold standard of match balls, renowned for retaining swing, shape, and prominent seam over 80+ overs of rigorous match play.",
    images: [
      "/images/products/IMG-20230731-WA0070.jpg",
      "/images/products/IMG-20230731-WA0071.jpg",
      "/images/products/IMG-20230731-WA0072.jpg",
    ],
  },
] as const;

export const products = sampleProducts;

export const categories = [
  { name: "Cricket Bats", href: "/products?category=bats", count: "30+ items" },
  { name: "Batting Pads", href: "/products?category=pads", count: "15+ items" },
  { name: "Batting Gloves", href: "/products?category=gloves", count: "20+ items" },
  { name: "Helmets", href: "/products?category=helmets", count: "10+ items" },
  { name: "Kit Bags", href: "/products?category=bags", count: "12+ items" },
  { name: "Cricket Shoes", href: "/products?category=shoes", count: "18+ items" },
  { name: "Balls & Accessories", href: "/products?category=balls", count: "25+ items" },
] as const;

export const testimonials = [
  {
    id: 1,
    name: "Devesh Sharma",
    role: "Club Cricketer",
    content: "The English willow bats are authentic and have an unbelievable ping. Exactly what I needed for tournament season.",
    rating: 5,
    avatar: "/images/Profile.png",
  },
  {
    id: 2,
    name: "Rizky Ramadhan",
    role: "Fast Bowler",
    content: "Protection level on the Shrey helmet and MRF pads is top notch. Delivery to Jakarta was fast and well-packaged.",
    rating: 5,
    avatar: "/images/Profile.png",
  },
  {
    id: 3,
    name: "Arjun Verma",
    role: "Cricket Academy Coach",
    content: "Ordered 5 boxes of Dukes match balls and several SG gloves. Premium quality and 100% original merchandise.",
    rating: 5,
    avatar: "/images/Profile.png",
  },
] as const;

export type Category = (typeof categories)[number];
export type Testimonial = (typeof testimonials)[number];
